config/routes.rb
Rails.application.routes.draw do
  get 'site/index'
  devise_for :users
  devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :invoices
  resources :records

  resources :projects do 
    resources :records
    resources :invoices
  end	  

  resources :customers do 
    resources :invoices
    resources :projects
  end

  root 'site#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/invoice.rb
class Invoice < ApplicationRecord
belongs_to :customer
validates :tot_hours, presence:true, numericality: { only_integer: true}
validates :cost_per_hour, presence:true, numericality: true
validates :description, presence:true
validates :customer_id, presence:true ,numericality: { only_integer: true}
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @customer = Customer.find(params[:customer_id])
    @invoices = @customer.invoices    
  end

  def show
  end

  def new
    if params[:project_id].nil?
     @tot_hours=0
     @customer = Customer.find(params[:customer_id])
     @customer.projects.each do |p|
       logger.debug "Record: #{p.records.sum(:hours).to_i}"
       @tot_hours+=p.records.sum(:hours).to_i
     end

    else
     @project = Project.find(params[:project_id])
     @customer = @project.customer
     @tot_hours = @project.records.sum(:hours)
    end

    @invoice = Invoice.new
    @invoice.tot_hours = @tot_hours
  end

  def edit
    @customer = Customer.find(params[:customer_id]) 
    @tot_hours = @invoice.tot_hours
  end

  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to root_path, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html {
	        if invoice_params[:customer_id]	
	        @customer = Customer.find(invoice_params[:customer_id])
		end
                if invoice_params[:project_id]
		@project = Project.find(invoice_params[:project_id])
                end
		render :new
	}
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to root_path, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:tot_hours, :cost_per_hour, :description, :customer_id, :project_id)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= simple_form_for(@invoice) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
	  <%= f.input :tot_hours, :value => @tot_hours, :as => :string, label:'Total Hours Worked' %>
	  <%= f.input :cost_per_hour, label:"Cost per hour (€)", :as => :string %>
    <%= f.input :description %>
    <%= f.hidden_field :customer_id, :value => @customer.id %>


  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', root_path %>

app/views/invoices/index.html.erb
<h1>Invoices (Customer: <%= @customer.name %>)</h1>

<table>
  <thead>
    <tr>
      <th>Total Hours Worked</th>
      <th>Cost per hour</th>
      <th>Description</th>
      <th>Invoice Amount</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.tot_hours %></td>
        <td><%= invoice.cost_per_hour %></td>
        <td><%= invoice.description %></td>
	<td><%= (invoice.tot_hours*invoice.cost_per_hour).to_f %>€</td>
        <td><%= invoice.created_at %></td>
        <td><%= link_to 'Show', customer_invoice_path(invoice.customer,invoice) %></td>
        <td><%= link_to 'Edit', edit_customer_invoice_path(invoice.customer,invoice) %></td>
        <td><%= link_to 'Destroy', customer_invoice_path(invoice.customer,invoice), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', root_path %>

app/views/invoices/new.html.erb
<h1>New Invoice (Customer: <%= @customer.name %> )</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', root_path %>

app/views/invoices/show.html.erb
<p>
  <strong>Total Hours Worked:</strong>
  <%= @invoice.tot_hours %>
</p>

<p>
  <strong>Cost per hour:</strong>
  <%= @invoice.cost_per_hour %>
</p>

<p>
  <strong>Invoice Amount:</strong>
  <%= (@invoice.tot_hours*@invoice.cost_per_hour).to_f %>€
</p>

<p>
  <strong>Description:</strong>
  <%= @invoice.description %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @invoice.customer.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @invoice.created_at %>
</p>


<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', root_path %>