config/routes.rb
Rails.application.routes.draw do
  get 'site/index'
  devise_for :users
  devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :invoices
  resources :records

  resources :projects do 
    resources :records
    resources :invoices
  end	  

  resources :customers do 
    resources :invoices
    resources :projects
  end

  root 'site#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/record.rb
class Record < ApplicationRecord
   belongs_to :project

   validates :project_id, presence:true
   validates :hours, presence:true, numericality: true
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  def index
    @project = Project.find(params[:project_id])
    @records = @project.records 
  end

  def show
  end

  def new
    @project = Project.find(params[:project_id])
    @record = Record.new
  end

  def edit
	  @project = Project.find(params[:project_id])
  end

  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to root_path, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { 
		@project = Project.find(record_params[:project_id])
		render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to root_path, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:hours, :description, :project_id)
    end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= simple_form_for(@record) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :hours %>
    <%= f.input :description %>
    <%= f.hidden_field :project_id, :value => @project.id %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing Record</h1>

<%= render 'form', record: @record %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', root_path %>

app/views/records/index.html.erb
<h1>Records for: <%= @project.name %></h1>

<table>
  <thead>
    <tr>
      <th>Hours</th>
      <th>Description</th>
      <th>Project</th>
      <th>Record Date </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.hours %></td>
        <td><%= record.description %></td>
	<td><%= record.project.name %></td>
        <td><%= record.created_at %></td>
        <td><%= link_to 'Show', project_record_url(record.project,record) %></td>
        <td><%= link_to 'Edit', edit_project_record_path(record.project,record) %></td>
        <td><%= link_to 'Destroy', project_record_url(record.project,record), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', root_path %>

app/views/records/new.html.erb
<h1>New Time Record For: <%= @project.name %></h1>

<%= render 'form', record: @record %>

<%= link_to 'Back', root_path %>

app/views/records/show.html.erb
<p>
  <strong>Hours:</strong>
  <%= @record.hours %>
</p>

<p>
  <strong>Description:</strong>
  <%= @record.description %>
</p>

<p>
  <strong>Project:</strong>
  <%= @record.project.name %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', root_path %>