config/routes.rb
Rails.application.routes.draw do
  get 'site/index'
  devise_for :users
  devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :invoices
  resources :records

  resources :projects do 
    resources :records
    resources :invoices
  end	  

  resources :customers do 
    resources :invoices
    resources :projects
  end

  root 'site#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    if user_signed_in?
      @projects = current_user.projects
      @customers = current_user.customers
    end
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/site/index.html.erb
<% if current_user %>
  <h2>Your Customers:</h2>
  <table style="width: 100%;">
    <thead>
      <tr>
        <th>Name</th>
	<th># Invoices</th>
	<th></th>
      </tr>
    </thead>

    <tbody>
       <% @customers.each do |customer| %>
        <tr>
	 <td><%= link_to customer.name, customer_path(customer) %></td>
	 <td><%= link_to "#{customer.invoices.count}", customer_invoices_path(customer) %></td>
	 <td><% if !customer.projects.empty? %> <%= link_to '<button>Create Invoice For This Customer</button>'.html_safe, new_customer_invoice_path(customer) %> <% end %> </td>
	</tr>
      <% end %>
    </tbody>
  </table>
  <div style="float:left;"><%= link_to 'Create New Customer ', new_customer_path %></div>
  <div style="float:left;margin-left:5px;"><%= link_to '| Manage Customers', customers_path %></div>
  <br>
  <br>
  <% if !current_user.customers.empty? %>
  <h2>Your Projects:</h2>
  <table style="width: 100%;">
    <thead>
      <tr>
        <th>Name</th>
        <th>Customer</th>
        <th>Hours Spent</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
       <% @projects.each do |project| %>
        <tr>
          <td><%= link_to project.name, project_path(project) %></td>
          <td><%= link_to project.customer.name, customer_path(project.customer) %></td>
          <td><%= link_to "#{project.records.sum(:hours)}", project_records_path(project) %></td>
          <td><%= link_to '<button>Add New Time Record</button>'.html_safe, new_project_record_path(project) %></td>
          <td><%= link_to '<button>Create Invoice For This Project</button>'.html_safe, new_project_invoice_path(project) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div style="float:left;"><%= link_to 'Create New Project ', new_project_path %></div>
  <div style="float:left;margin-left:5px;"><%= link_to '| Manage Projects', projects_path %></div>
  <br>
  <% else %> 
	  <div class="float:left;"><u>First create a customer, then you'll be able to create as many project you want!</u></div>
	  <br>
  <% end %>

<% else %>
  <div class="panel">
    <h1>Welcome to Timetrack!</h1>
    <p>A simple app to track time you spend working on your freelance projects.</p>
    <%= link_to "<button>Register</button>".html_safe, new_user_registration_path %>
    <%= link_to "<button>Login</button>".html_safe, new_user_session_path %>

  </div>

  <hr>

<% end %>